version: '3'
services:
  node:
    stdin_open: true
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd reactapp && npm install && npm start"
    ports:
      - "3000:3000"